namespace Fortuna.Infrastructure.Data
{
    public class RandomListValuePersonCity : RandomListValue<string>
    {
        public RandomListValuePersonCity()
        {
            // Source: https://pt.wikipedia.org/wiki/Lista_de_cidades_em_Portugal
            names.Add("Abrantes");
            names.Add("Agualva-Cacém");
            names.Add("Albergaria-a-Velha");
            names.Add("Albufeira");
            names.Add("Alcobaça");
            names.Add("Alcácer do Sal");
            names.Add("Alfena");
            names.Add("Almada");
            names.Add("Almeirim");
            names.Add("Alverca do Ribatejo");
            names.Add("Amadora");
            names.Add("Amarante");
            names.Add("Amora");
            names.Add("Anadia");
            names.Add("Angra do Heroísmo");
            names.Add("Aveiro");
            names.Add("Barcelos");
            names.Add("Barreiro");
            names.Add("Beja");
            names.Add("Borba");
            names.Add("Braga");
            names.Add("Bragança");
            names.Add("Caldas da Rainha");
            names.Add("Caniço");
            names.Add("Cantanhede");
            names.Add("Cartaxo");
            names.Add("Castelo Branco");
            names.Add("Chaves");
            names.Add("Coimbra");
            names.Add("Costa da Caparica");
            names.Add("Covilhã");
            names.Add("Câmara de Lobos");
            names.Add("Elvas");
            names.Add("Entroncamento");
            names.Add("Ermesinde");
            names.Add("Esmoriz");
            names.Add("Espinho");
            names.Add("Esposende");
            names.Add("Estarreja");
            names.Add("Estremoz");
            names.Add("Fafe");
            names.Add("Faro");
            names.Add("Felgueiras");
            names.Add("Figueira da Foz");
            names.Add("Fiães");
            names.Add("Freamunde");
            names.Add("Funchal");
            names.Add("Fundão");
            names.Add("Fátima");
            names.Add("Gafanha da Nazaré");
            names.Add("Gandra");
            names.Add("Gondomar");
            names.Add("Gouveia");
            names.Add("Guarda");
            names.Add("Guimarães");
            names.Add("Horta");
            names.Add("Lagoa");
            names.Add("Lagos");
            names.Add("Lamego");
            names.Add("Leiria");
            names.Add("Lisboa");
            names.Add("Lixa");
            names.Add("Lordelo");
            names.Add("Loulé");
            names.Add("Loures");
            names.Add("Lourosa");
            names.Add("Macedo de Cavaleiros");
            names.Add("Machico");
            names.Add("Maia");
            names.Add("Mangualde");
            names.Add("Marco de Canaveses");
            names.Add("Marinha Grande");
            names.Add("Matosinhos");
            names.Add("Mealhada");
            names.Add("Miranda do Douro / Miranda de l Douro");
            names.Add("Mirandela");
            names.Add("Montemor-o-Novo");
            names.Add("Montijo");
            names.Add("Moura");
            names.Add("Mêda");
            names.Add("Odivelas");
            names.Add("Olhão da Restauração");
            names.Add("Oliveira de Azeméis");
            names.Add("Oliveira do Bairro");
            names.Add("Oliveira do Hospital");
            names.Add("Ourém");
            names.Add("Ovar");
            names.Add("Paredes");
            names.Add("Paços de Ferreira");
            names.Add("Penafiel");
            names.Add("Peniche");
            names.Add("Peso da Régua");
            names.Add("Pinhel");
            names.Add("Pombal");
            names.Add("Ponta Delgada");
            names.Add("Ponte de Sor");
            names.Add("Portalegre");
            names.Add("Portimão");
            names.Add("Porto");
            names.Add("Praia da Vitória");
            names.Add("Póvoa de Santa Iria");
            names.Add("Póvoa de Varzim");
            names.Add("Quarteira");
            names.Add("Queluz");
            names.Add("Rebordosa");
            names.Add("Reguengos de Monsaraz");
            names.Add("Ribeira Grande");
            names.Add("Rio Maior");
            names.Add("Rio Tinto");
            names.Add("Sabugal");
            names.Add("Sacavém");
            names.Add("Samora Correia");
            names.Add("Santa Comba Dão");
            names.Add("Santa Cruz");
            names.Add("Santa Maria da Feira");
            names.Add("Santana");
            names.Add("Santarém");
            names.Add("Santiago do Cacém");
            names.Add("Santo Tirso");
            names.Add("Seia");
            names.Add("Seixal");
            names.Add("Senhora da Hora");
            names.Add("Serpa");
            names.Add("Setúbal");
            names.Add("Silves");
            names.Add("Sines");
            names.Add("São João da Madeira");
            names.Add("São Mamede de Infesta");
            names.Add("São Pedro do Sul");
            names.Add("Tarouca");
            names.Add("Tavira");
            names.Add("Tomar");
            names.Add("Tondela");
            names.Add("Torres Novas");
            names.Add("Torres Vedras");
            names.Add("Trancoso");
            names.Add("Trofa");
            names.Add("Valbom");
            names.Add("Vale de Cambra");
            names.Add("Valença");
            names.Add("Valongo");
            names.Add("Valpaços");
            names.Add("Vendas Novas");
            names.Add("Viana do Castelo");
            names.Add("Vila Baleira");
            names.Add("Vila do Conde");
            names.Add("Vila Franca de Xira");
            names.Add("Vila Nova de Famalicão");
            names.Add("Vila Nova de Foz Côa");
            names.Add("Vila Nova de Gaia");
            names.Add("Vila Nova de Santo André");
            names.Add("Vila Real");
            names.Add("Vila Real de Santo António");
            names.Add("Viseu");
            names.Add("Vizela");
            names.Add("Águeda");
            names.Add("Évora");
            names.Add("Ílhavo");
        }
    }
}
