namespace Fortuna.Infrastructure.Data
{
    public class RandomListValuePersonSurname : RandomListValue<string>
    {
        public RandomListValuePersonSurname()
        {
            names.Add("Andrade");
            names.Add("Antunes");
            names.Add("Araújo");
            names.Add("Assunção");
            names.Add("Azevedo");
            names.Add("Borges");
            names.Add("Brito");
            names.Add("Cardoso");
            names.Add("Carvalho");
            names.Add("Castro");
            names.Add("Costa");
            names.Add("Cunha");
            names.Add("Dias");
            names.Add("Dinis");
            names.Add("Fernandes");
            names.Add("Ferreira");
            names.Add("Fonseca");
            names.Add("Freitas");
            names.Add("Gomes");
            names.Add("Gonçalves");
            names.Add("Henriques");
            names.Add("Leal");
            names.Add("Lima");
            names.Add("Magalhães");
            names.Add("Martins");
            names.Add("Matos");
            names.Add("Morais");
            names.Add("Moreira");
            names.Add("Mota");
            names.Add("Moura");
            names.Add("Oliveira");
            names.Add("Pacheco");
            names.Add("Pereira");
            names.Add("Pinho");
            names.Add("Pinto");
            names.Add("Pires");
            names.Add("Proença");
            names.Add("Ramos");
            names.Add("Ribeiro");
            names.Add("Santos");
            names.Add("Sequeira");
            names.Add("Silva");
            names.Add("Soares");
            names.Add("Tavares");
            names.Add("Viana");
            names.Add("Vieira");
        }
    }
}
