namespace Fortuna.Infrastructure.Data
{
    public class RandomListValuePersonName : RandomListValue
    {
        public RandomListValuePersonName()
        {
            names.Add("Abel");
            names.Add("Ana");
            names.Add("Andreia");
            names.Add("André");
            names.Add("Antónia");
            names.Add("António");
            names.Add("Artur");
            names.Add("Baltazar");
            names.Add("Beatriz");
            names.Add("Carminda");
            names.Add("Catarina");
            names.Add("Cláudia");
            names.Add("Cláudio");
            names.Add("Conceição");
            names.Add("Cristiano");
            names.Add("Cristina");
            names.Add("Célia");
            names.Add("Daniel");
            names.Add("Daniela");
            names.Add("Edgar");
            names.Add("Edite");
            names.Add("Eduarda");
            names.Add("Eduardo");
            names.Add("Filipa");
            names.Add("Filipe");
            names.Add("Fátima");
            names.Add("Glória");
            names.Add("Gonçalo");
            names.Add("Gustavo");
            names.Add("Hugo");
            names.Add("Hélder");
            names.Add("Igor");
            names.Add("Isabel");
            names.Add("Ivo");
            names.Add("Ivone");
            names.Add("Joana");
            names.Add("Jorge");
            names.Add("José");
            names.Add("João");
            names.Add("Julieta");
            names.Add("Júlia");
            names.Add("Júlio");
            names.Add("Kendal");
            names.Add("Lara");
            names.Add("Leandro");
            names.Add("Leonor");
            names.Add("Luís");
            names.Add("Luísa");
            names.Add("Manuel");
            names.Add("Maria");
            names.Add("Mariana");
            names.Add("Martim");
            names.Add("Miguel");
            names.Add("Mário");
            names.Add("Nuno");
            names.Add("Olga");
            names.Add("Otávio");
            names.Add("Patrícia");
            names.Add("Patrício");
            names.Add("Paulo");
            names.Add("Pedro");
            names.Add("Ricardo");
            names.Add("Rodrigo");
            names.Add("Romeu");
            names.Add("Rui");
            names.Add("Sandra");
            names.Add("Sandro");
            names.Add("Sara");
            names.Add("Sílvia");
            names.Add("Sílvio");
            names.Add("Telmo");
            names.Add("Tiago");
            names.Add("Tomás");
            names.Add("Tomé");
            names.Add("Ulisses");
            names.Add("Valter");
            names.Add("Xavier");
            names.Add("Yara");
            names.Add("Álvaro");
            names.Add("Óscar");
            names.Add("Ósvaldo");
        }
    }
}
