using System.Collections.Generic;

namespace Fortuna.Infrastructure.Data
{
    public class RandomListValueComment : RandomListValue<string>
    {
        public RandomListValueComment()
        {
            names.Add("accumsan");
            names.Add("adipiscing");
            names.Add("aenean");
            names.Add("aliqua");
            names.Add("aliquam");
            names.Add("aliquet");
            names.Add("amet");
            names.Add("ante");
            names.Add("arcu");
            names.Add("at");
            names.Add("auctor");
            names.Add("augue");
            names.Add("bibendum");
            names.Add("blandit");
            names.Add("commodo");
            names.Add("condimentum");
            names.Add("congue");
            names.Add("consectetur");
            names.Add("consequat");
            names.Add("convallis");
            names.Add("cras");
            names.Add("cum");
            names.Add("curabitur");
            names.Add("cursus");
            names.Add("dapibus");
            names.Add("diam");
            names.Add("dictum");
            names.Add("dictumst");
            names.Add("dignissim");
            names.Add("dis");
            names.Add("do");
            names.Add("dolor");
            names.Add("dolore");
            names.Add("donec");
            names.Add("dui");
            names.Add("duis");
            names.Add("egestas");
            names.Add("eget");
            names.Add("eiusmod");
            names.Add("eleifend");
            names.Add("elementum");
            names.Add("elit");
            names.Add("enim");
            names.Add("erat");
            names.Add("eros");
            names.Add("est");
            names.Add("et");
            names.Add("etiam");
            names.Add("eu");
            names.Add("euismod");
            names.Add("facilisi");
            names.Add("facilisis");
            names.Add("fames");
            names.Add("faucibus");
            names.Add("felis");
            names.Add("fermentum");
            names.Add("feugiat");
            names.Add("fringilla");
            names.Add("fusce");
            names.Add("gravida");
            names.Add("habitant");
            names.Add("habitasse");
            names.Add("hac");
            names.Add("hendrerit");
            names.Add("iaculis");
            names.Add("id");
            names.Add("imperdiet");
            names.Add("in");
            names.Add("incididunt");
            names.Add("integer");
            names.Add("interdum");
            names.Add("ipsum");
            names.Add("justo");
            names.Add("labore");
            names.Add("lacinia");
            names.Add("lacus");
            names.Add("laoreet");
            names.Add("lectus");
            names.Add("leo");
            names.Add("libero");
            names.Add("ligula");
            names.Add("lobortis");
            names.Add("lorem");
            names.Add("luctus");
            names.Add("maecenas");
            names.Add("magna");
            names.Add("magnis");
            names.Add("malesuada");
            names.Add("massa");
            names.Add("mattis");
            names.Add("mauris");
            names.Add("metus");
            names.Add("mi");
            names.Add("molestie");
            names.Add("mollis");
            names.Add("montes");
            names.Add("morbi");
            names.Add("mus");
            names.Add("nam");
            names.Add("nascetur");
            names.Add("natoque");
            names.Add("nec");
            names.Add("neque");
            names.Add("netus");
            names.Add("nibh");
            names.Add("nisi");
            names.Add("nisl");
            names.Add("non");
            names.Add("nulla");
            names.Add("nullam");
            names.Add("nunc");
            names.Add("odio");
            names.Add("orci");
            names.Add("ornare");
            names.Add("parturient");
            names.Add("pellentesque");
            names.Add("penatibus");
            names.Add("pharetra");
            names.Add("phasellus");
            names.Add("placerat");
            names.Add("platea");
            names.Add("porta");
            names.Add("porttitor");
            names.Add("posuere");
            names.Add("potenti");
            names.Add("praesent");
            names.Add("pretium");
            names.Add("proin");
            names.Add("pulvinar");
            names.Add("purus");
            names.Add("quam");
            names.Add("quis");
            names.Add("quisque");
            names.Add("rhoncus");
            names.Add("ridiculus");
            names.Add("risus");
            names.Add("rutrum");
            names.Add("sagittis");
            names.Add("sapien");
            names.Add("scelerisque");
            names.Add("sed");
            names.Add("sem");
            names.Add("semper");
            names.Add("senectus");
            names.Add("sit");
            names.Add("sociis");
            names.Add("sodales");
            names.Add("sollicitudin");
            names.Add("suscipit");
            names.Add("suspendisse");
            names.Add("tellus");
            names.Add("tempor");
            names.Add("tempus");
            names.Add("tincidunt");
            names.Add("tortor");
            names.Add("tristique");
            names.Add("turpis");
            names.Add("ullamcorper");
            names.Add("ultrices");
            names.Add("ultricies");
            names.Add("urna");
            names.Add("ut");
            names.Add("varius");
            names.Add("vehicula");
            names.Add("vel");
            names.Add("velit");
            names.Add("venenatis");
            names.Add("vestibulum");
            names.Add("vitae");
            names.Add("vivamus");
            names.Add("viverra");
            names.Add("volutpat");
            names.Add("vulputate");
        }

        public override string GetRandomValue()
        {
            var result = new List<string>();

            for (int i = 0; i < 20; i++)
            {
                result.Add(base.GetRandomValue());
            }

            return string.Join(' ', result.ToArray()).ToTitleSentence();
        }
    }
}
